import { Check, Clipboard, Eye, EyeOff, Play } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useConsoleLanguage } from '../../../app/ConsoleLanguage'
import type { GenerationStatus, RunnerSubmissionIdentity } from '../types'

type GeneratedDslPanelProps = {
  draftStorageFailed: boolean
  canRun: boolean
  isValidating: boolean
  isGenerating: boolean
  onEdit: (value: string) => void
  onValidate: () => void
  validationMessage: string | null
  dsl: string
  generatedBy: string
  generationError?: string | null
  generationStatus: GenerationStatus | null
  isSubmitting: boolean
  onRun: () => void
  onViewRun: (runId: number) => void
  repairAttempts: number
  runnerError: string | null
  runnerSubmission: RunnerSubmissionIdentity | null
}

export function GeneratedDslPanel({ draftStorageFailed, isValidating, isGenerating, onEdit, onValidate, validationMessage, canRun, dsl, generatedBy, generationError, generationStatus, isSubmitting, onRun, onViewRun, repairAttempts, runnerError, runnerSubmission }: GeneratedDslPanelProps) {
  const { ui, language } = useConsoleLanguage()
  const [copied, setCopied] = useState(false)
  const [isVisible, setIsVisible] = useState(Boolean(dsl))

  useEffect(() => {
    if (dsl) setIsVisible(true)
  }, [dsl])

  const copyDsl = async () => {
    if (!dsl) return

    try {
      await navigator.clipboard?.writeText(dsl)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1500)
    } catch {
      setCopied(false)
    }
  }

  return (
    <section className="generated-dsl-panel" aria-labelledby="generated-dsl-title">
      <header className="dsl-heading">
        <div>
          <span className="studio-eyebrow">{ui('Shared TestCase DSL')}</span>
          <h2 id="generated-dsl-title">{ui('Final TestCase DSL')}</h2>
        </div>
        <div className="dsl-actions">
          <button className="panel-action" disabled={!dsl || isSubmitting || isValidating || isGenerating} onClick={onValidate} type="button">
            <Check size={14} />{isValidating ? (language === 'zh-CN' ? '校验中…' : 'Validating...') : (language === 'zh-CN' ? 'Java 校验' : 'Validate with Java')}
          </button>
          <button className="panel-action" disabled={!canRun || isSubmitting} onClick={onRun} type="button">
            <Play size={14} strokeWidth={1.8} />
            {isSubmitting ? ui('Submitting...') : ui('Run Test')}
          </button>
          <button aria-expanded={isVisible} className="panel-action" disabled={!dsl} onClick={() => setIsVisible((value) => !value)} type="button">
            {isVisible ? <EyeOff size={14} strokeWidth={1.8} /> : <Eye size={14} strokeWidth={1.8} />}
            {ui('View')}
          </button>
          <button className="panel-action" disabled={!dsl} onClick={copyDsl} type="button">
            {copied ? <Check size={14} strokeWidth={1.8} /> : <Clipboard size={14} strokeWidth={1.8} />}
            {copied ? ui('Copied') : ui('Copy')}
          </button>
        </div>
      </header>

      {dsl && <div className="dsl-meta" role="status">
        {draftStorageFailed
          ? (language === 'zh-CN' ? '草稿暂存于当前页面会话；浏览器存储不可用，刷新前请复制备份。' : 'Draft retained in memory. Browser storage is unavailable; copy it before refreshing.')
          : (language === 'zh-CN' ? '草稿保存在此标签页，刷新后可恢复；退出登录后清除。' : 'Draft saved in this tab and restored after refresh; cleared on sign out.')}
      </div>}

      {(generatedBy || generationError || repairAttempts > 0) && (
        <div className={`dsl-meta${generationError ? ' is-error' : ''}`}>
          <span>{generationError ?? (generatedBy ? `${ui('Generated by')} ${generatedBy}` : ui('Generation result'))}</span>
          {repairAttempts > 0 && <small>{ui('Repair attempt')} {repairAttempts}</small>}
          {generationStatus === 'ACCEPTED' && <small>{ui('Accepted')}</small>}
          {generationStatus === 'REJECTED' && <small>{ui('Rejected')}</small>}
          {generationStatus === 'FAILED' && <small>{ui('Failed')}</small>}
        </div>
      )}

      {validationMessage && <div className={`dsl-meta${generationStatus === 'REJECTED' ? ' is-error' : ''}`} role="status" style={{ whiteSpace: 'pre-wrap' }}>{ui(validationMessage)}</div>}

      {runnerSubmission ? (
        <div className="dsl-meta" role="status">
          <span>{ui('Submitted to Java Runner')} · Run #{runnerSubmission.runId}</span>
          <small>Task #{runnerSubmission.taskId}</small>
          <button className="panel-action" onClick={() => onViewRun(runnerSubmission.runId)} type="button">{ui('View Run')}</button>
        </div>
      ) : runnerError ? <div className="dsl-meta is-error" role="alert">{runnerError}</div> : null}

      {isVisible ? (
        <textarea aria-label={ui('TestCase DSL editor')} className="code-block dsl-code" value={dsl}
          onChange={(event) => onEdit(event.target.value)} disabled={isSubmitting || isGenerating}
          spellCheck={false} rows={22} style={{ width: '100%', boxSizing: 'border-box', resize: 'vertical', fontFamily: 'monospace' }} />
      ) : (
        <div className="dsl-empty-state">{ui('Generate a TestCase to inspect the final shared DSL.')}</div>
      )}
    </section>
  )
}
