import { Check, Clipboard, Eye, EyeOff } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useConsoleLanguage } from '../../../app/ConsoleLanguage'
import type { GenerationStatus } from '../types'

type GeneratedDslPanelProps = {
  dsl: string
  generatedBy: string
  generationError?: string | null
  generationStatus: GenerationStatus | null
  repairAttempts: number
}

export function GeneratedDslPanel({ dsl, generatedBy, generationError, generationStatus, repairAttempts }: GeneratedDslPanelProps) {
  const { ui } = useConsoleLanguage()
  const [copied, setCopied] = useState(false)
  const [isVisible, setIsVisible] = useState(Boolean(dsl))

  useEffect(() => {
    setIsVisible(Boolean(dsl))
  }, [dsl])

  const copyDsl = async () => {
    if (!dsl) return

    try {
      await navigator.clipboard?.writeText(dsl)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1500)
    } catch {
      setCopied(false)
    }
  }

  return (
    <section className="generated-dsl-panel" aria-labelledby="generated-dsl-title">
      <header className="dsl-heading">
        <div>
          <span className="studio-eyebrow">{ui('Shared TestCase DSL')}</span>
          <h2 id="generated-dsl-title">{ui('Final TestCase DSL')}</h2>
        </div>
        <div className="dsl-actions">
          <button aria-expanded={isVisible} className="panel-action" disabled={!dsl} onClick={() => setIsVisible((value) => !value)} type="button">
            {isVisible ? <EyeOff size={14} strokeWidth={1.8} /> : <Eye size={14} strokeWidth={1.8} />}
            {ui('View')}
          </button>
          <button className="panel-action" disabled={!dsl} onClick={copyDsl} type="button">
            {copied ? <Check size={14} strokeWidth={1.8} /> : <Clipboard size={14} strokeWidth={1.8} />}
            {copied ? ui('Copied') : ui('Copy')}
          </button>
        </div>
      </header>

      {(generatedBy || generationError || repairAttempts > 0) && (
        <div className={`dsl-meta${generationError ? ' is-error' : ''}`}>
          <span>{generationError ?? (generatedBy ? `${ui('Generated by')} ${generatedBy}` : ui('Generation result'))}</span>
          {repairAttempts > 0 && <small>{ui('Repair attempt')} {repairAttempts}</small>}
          {generationStatus === 'ACCEPTED' && <small>{ui('Accepted')}</small>}
          {generationStatus === 'REJECTED' && <small>{ui('Rejected')}</small>}
          {generationStatus === 'FAILED' && <small>{ui('Failed')}</small>}
        </div>
      )}

      {isVisible && dsl ? (
        <pre className="code-block dsl-code"><code>{dsl}</code></pre>
      ) : (
        <div className="dsl-empty-state">{ui('Generate a TestCase to inspect the final shared DSL.')}</div>
      )}
    </section>
  )
}
