import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type ConsoleLanguage = 'en' | 'zh-CN'

export const LANGUAGE_STORAGE_KEY = 'apiops-console-language'

type Copy = Record<string, string>

const translations: Record<ConsoleLanguage, Copy> = {
  en: {
    'nav.overview': 'Overview',
    'nav.apiStudio': 'API Studio',
    'nav.runs': 'Runs',
    'nav.diagnosisStudio': 'Diagnosis Studio',
    'nav.diagnosis': 'Diagnosis',
    'nav.traces': 'Traces',
    'nav.evaluation': 'Evaluation',
    'nav.settings': 'Settings',
    'common.collapse': 'Collapse',
    'common.expand': 'Expand',
    'common.switchToLightTheme': 'Switch to light theme',
    'common.switchToDarkTheme': 'Switch to dark theme',
    'common.userMenu': 'User menu',
    'common.copy': 'Copy',
    'common.retry': 'Retry',
    'auth.signInTitle': 'Sign in to your workspace',
    'auth.loginDescription': 'Access your Agentic APIOps console to manage APIs and agent workflows.',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.usernamePlaceholder': 'Enter your username',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.signIn': 'Sign in',
    'auth.signingIn': 'Signing in...',
    'auth.invalidCredentials': 'Invalid username or password.',
    'auth.genericFailure': 'Unable to sign in. Try again later.',
    'auth.networkFailure': 'Unable to reach Java Platform. Check the connection and try again.',
    'auth.restoringSessionTitle': 'Restoring your session',
    'auth.restoringSessionDescription': 'Checking the current Java Platform session.',
    'auth.sessionExpiredTitle': 'Session expired',
    'auth.sessionExpiredDescription': 'Your session is no longer valid. Sign in again to continue.',
    'auth.signInAgain': 'Sign in',
    'auth.javaAuthNotice': 'Sign in is handled by Java Platform authentication.',
    'auth.javaSession': 'Current user loaded from Java Platform.',
    'auth.javaPlatformBadge': 'JAVA',
    'auth.userId': 'User ID',
    'auth.internalDeveloperPlatform': 'Internal developer platform',
    'auth.signOut': 'Sign out',
    'auth.languageSwitchToEnglish': 'Switch to English',
    'auth.languageSwitchToChinese': 'Switch to Chinese',
    'auth.accessDeniedTitle': 'Access denied',
    'auth.accessDeniedDescription': "You don't have permission to access this project.",
    'project.currentProject': 'Current Project',
    'project.projects': 'Projects',
    'project.project': 'Project',
    'project.access': 'Access',
    'project.role.OWNER': 'OWNER',
    'project.role.EDITOR': 'EDITOR',
    'project.role.VIEWER': 'VIEWER',
    'project.accessDenied': 'No access',
    'project.switchProject': 'Switch project',
    'project.loadingProjects': 'Loading projects',
    'project.loadingProjectsDescription': 'Loading projects available to the authenticated user.',
    'project.failedToLoad': 'Projects unavailable',
    'project.failedToLoadDescription': 'The accessible project list could not be loaded.',
    'project.noAccessibleProjects': 'No accessible projects',
    'project.noAccessibleProjectsDescription': 'This authenticated user has no project membership available in Java Platform.',
    'project.noProjectSelected': 'No project selected',
    'page.overview.title': 'Overview',
    'page.overview.description': 'Monitor your APIs, agents, and system health at a glance.',
    'page.apiStudio.title': 'API Studio',
    'page.apiStudio.description': 'Explore API metadata, inspect contracts, and generate test cases for your endpoints.',
    'page.runs.title': 'Runs',
    'page.runs.description': 'Track test executions, inspect runtime results, and investigate assertion or execution failures.',
    'runs.loading': 'Loading runs',
    'runs.loadingDescription': 'Reading recent Java Runner executions for the current project.',
    'runs.failedToLoad': 'Runs unavailable',
    'runs.failedToLoadDescription': 'The project-scoped Run list could not be loaded.',
    'runs.noRuns': 'No runs yet',
    'runs.noRunsDescription': 'This project has no persisted test executions to display.',
    'runs.noRunSelected': 'Select a run to inspect its TestReport.',
    'runs.loadingReport': 'Loading TestReport',
    'runs.reportUnavailable': 'Report not available yet',
    'runs.reportUnavailableDescription': 'Java Platform has not made a TestReport available for this run.',
    'runs.failedToLoadReport': 'Failed to load TestReport',
    'runs.failedToLoadReportDescription': 'The TestReport could not be read from Java Platform.',
    'runs.retry': 'Retry',
    'runs.live': 'Live',
    'runs.disconnected': 'Live progress unavailable',
    'runs.disconnectedDescription': 'The persisted Run status is retained. Refresh to try the live stream again.',
    'runs.currentProgress': 'Current progress',
    'runs.progressCompleted': 'completed',
    'runs.noRequestSnapshot': 'The Java TestReport contract does not include a request snapshot.',
    'runs.noResponseSnapshot': 'The Java TestReport contract does not include a response body snapshot.',
    'runs.responseFacts': 'Response facts recorded by Java TestReport',
    'runs.noResponseFacts': 'No response facts are available from TestReport.',
    'runs.noAssertions': 'No assertion results are recorded in TestReport.',
    'runs.noTimeline': 'Timeline events are not included in the current Run read contract.',
    'runs.javaReportFacts': 'Execution facts supplied by Java Platform TestReport',
    'runs.status.PENDING': 'Run is waiting to start',
    'runs.status.RUNNING': 'Run is still in progress',
    'runs.status.SUCCESS': 'Run completed successfully',
    'runs.status.ASSERTION_FAILED': 'Run completed with assertion failures',
    'runs.status.EXECUTION_FAILED': 'Run failed during execution',
    'runs.status.TIMEOUT': 'Run timed out before completion',
    'runs.status.CANCELLED': 'Run was cancelled before completion',
    'page.diagnosisStudio.title': 'Diagnosis Studio',
    'page.diagnosisStudio.description': 'Run a diagnosis agent against the selected failed execution and inspect its workflow progress.',
    'page.diagnosis.title': 'Diagnosis',
    'page.diagnosis.description': 'Understand why a run failed, inspect the evidence, and identify the likely root cause.',
    'page.traces.title': 'Traces',
    'page.traces.description': 'Trace agent workflows, model calls, tool activity, and cross-system execution in one correlated view.',
    'page.evaluation.title': 'Evaluation',
    'page.evaluation.description': 'Inspect observed agent runtime executions, validation, tools, safety, latency, tokens, and cost.',
    'page.settings.title': 'Settings',
    'page.settings.description': 'Project configuration and console preferences',
    'settings.projectEnvironment': 'Project & Environment',
    'settings.platformConnections': 'Platform Connections',
    'settings.appearance': 'Appearance',
    'settings.diagnosisPreference': 'Diagnosis Preference',
    'settings.project': 'Project',
    'settings.environment': 'Environment',
    'settings.apiBaseUrl': 'API Base URL',
    'settings.demoProject': 'Demo Project',
    'settings.production': 'Production',
    'settings.javaPlatform': 'Java Platform',
    'settings.pythonAgentLab': 'Python AgentLab',
    'settings.javaDescription': 'APIOps Java agent for production telemetry and diagnostics.',
    'settings.pythonDescription': 'Python AgentLab SDK for experimentation and evaluation.',
    'settings.connected': 'Connected',
    'settings.manage': 'Manage',
    'settings.mockStatus': 'Status shown above is demo/frontend mock data.',
    'settings.theme': 'Theme',
    'settings.system': 'System',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.language': 'Language',
    'settings.chinese': '中文',
    'settings.english': 'English',
    'settings.compactDensity': 'Compact mode',
    'settings.compactDensityDescription': 'Reduce interface spacing to show more content on the same screen',
    'settings.reducedMotion': 'Reduce motion',
    'settings.reducedMotionDescription': 'Reduce non-essential animations and transitions across the console',
    'settings.autoDiagnose': 'Auto-diagnose failed runs',
    'settings.autoDiagnoseDescription': 'Automatically run diagnosis for failed runs when results are available.',
    'settings.frontendPreferenceNote': 'Stored as a frontend preference; it does not trigger backend jobs.',
    'settings.languageNote': 'Language setting applies only to the APIOps Console UI.',
    'settings.languageNoteDetail': 'Backend systems, agents, and platforms continue to use their own language.',
  },
  'zh-CN': {
    'nav.overview': '概览',
    'nav.apiStudio': 'API Studio',
    'nav.runs': '运行记录',
    'nav.diagnosisStudio': '诊断工作台',
    'nav.diagnosis': '诊断结果',
    'nav.traces': '追踪',
    'nav.evaluation': '评测',
    'nav.settings': '设置',
    'common.collapse': '收起',
    'common.expand': '展开',
    'common.switchToLightTheme': '切换到浅色主题',
    'common.switchToDarkTheme': '切换到深色主题',
    'common.userMenu': '用户菜单',
    'common.copy': '复制',
    'common.retry': '重试',
    'auth.signInTitle': '登录工作区',
    'auth.loginDescription': '访问 Agentic APIOps 控制台，管理 API 与 Agent 工作流。',
    'auth.username': '用户名',
    'auth.password': '密码',
    'auth.usernamePlaceholder': '输入用户名',
    'auth.passwordPlaceholder': '输入密码',
    'auth.signIn': '登录',
    'auth.signingIn': '正在登录...',
    'auth.invalidCredentials': '用户名或密码错误。',
    'auth.genericFailure': '无法完成登录，请稍后重试。',
    'auth.networkFailure': '无法连接 Java Platform，请检查连接后重试。',
    'auth.restoringSessionTitle': '正在恢复登录状态',
    'auth.restoringSessionDescription': '正在向 Java Platform 验证当前会话。',
    'auth.sessionExpiredTitle': '登录已过期',
    'auth.sessionExpiredDescription': '当前登录状态已失效，请重新登录后继续。',
    'auth.signInAgain': '重新登录',
    'auth.javaAuthNotice': '登录由 Java Platform 认证处理。',
    'auth.javaSession': '当前用户信息来自 Java Platform。',
    'auth.javaPlatformBadge': 'JAVA',
    'auth.userId': '用户 ID',
    'auth.internalDeveloperPlatform': '内部开发者平台',
    'auth.signOut': '退出登录',
    'auth.languageSwitchToEnglish': 'Switch to English',
    'auth.languageSwitchToChinese': '切换到中文',
    'auth.accessDeniedTitle': '无访问权限',
    'auth.accessDeniedDescription': '你没有权限访问当前项目。',
    'project.currentProject': '当前项目',
    'project.projects': '项目',
    'project.project': '项目',
    'project.access': '访问权限',
    'project.role.OWNER': 'OWNER',
    'project.role.EDITOR': 'EDITOR',
    'project.role.VIEWER': 'VIEWER',
    'project.accessDenied': '无访问权限',
    'project.switchProject': '切换项目',
    'project.loadingProjects': '正在加载项目',
    'project.loadingProjectsDescription': '正在加载当前登录用户可访问的项目。',
    'project.failedToLoad': '项目不可用',
    'project.failedToLoadDescription': '无法加载可访问项目列表。',
    'project.noAccessibleProjects': '没有可访问的项目',
    'project.noAccessibleProjectsDescription': '当前用户在 Java Platform 中没有可用的项目成员关系。',
    'project.noProjectSelected': '未选择项目',
    'page.overview.title': '概览',
    'page.overview.description': '一览监控 API、Agent 与系统健康状态。',
    'page.apiStudio.title': 'API Studio',
    'page.apiStudio.description': '探索 API 元数据、检查契约，并为端点生成测试用例。',
    'page.runs.title': '运行记录',
    'page.runs.description': '跟踪测试执行、查看运行结果，并调查断言或执行失败。',
    'runs.loading': '正在加载运行记录',
    'runs.loadingDescription': '正在读取当前项目最近的 Java Runner 执行记录。',
    'runs.failedToLoad': '运行记录不可用',
    'runs.failedToLoadDescription': '无法加载当前项目的运行记录列表。',
    'runs.noRuns': '暂无运行记录',
    'runs.noRunsDescription': '当前项目没有可展示的持久化测试执行记录。',
    'runs.noRunSelected': '选择一条运行记录以查看其 TestReport。',
    'runs.loadingReport': '正在加载 TestReport',
    'runs.reportUnavailable': 'TestReport 尚不可用',
    'runs.reportUnavailableDescription': 'Java Platform 尚未为此运行记录提供 TestReport。',
    'runs.failedToLoadReport': 'TestReport 加载失败',
    'runs.failedToLoadReportDescription': '无法从 Java Platform 读取 TestReport。',
    'runs.retry': '重试',
    'runs.live': '实时',
    'runs.disconnected': '实时进度不可用',
    'runs.disconnectedDescription': '已保留持久化运行状态，可刷新后重新尝试实时流。',
    'runs.currentProgress': '当前进度',
    'runs.progressCompleted': '已完成',
    'runs.noRequestSnapshot': 'Java TestReport 契约不包含请求快照。',
    'runs.noResponseSnapshot': 'Java TestReport 契约不包含响应正文快照。',
    'runs.responseFacts': 'Java TestReport 记录的响应事实',
    'runs.noResponseFacts': 'TestReport 中没有可用的响应事实。',
    'runs.noAssertions': 'TestReport 中未记录断言结果。',
    'runs.noTimeline': '当前 Run 读取契约不包含时间线事件。',
    'runs.javaReportFacts': '由 Java Platform TestReport 提供的执行事实',
    'runs.status.PENDING': '运行等待开始',
    'runs.status.RUNNING': '运行仍在进行中',
    'runs.status.SUCCESS': '运行已成功完成',
    'runs.status.ASSERTION_FAILED': '运行完成但存在断言失败',
    'runs.status.EXECUTION_FAILED': '运行执行失败',
    'runs.status.TIMEOUT': '运行超时未完成',
    'runs.status.CANCELLED': '运行在完成前已取消',
    'page.diagnosisStudio.title': '诊断工作台',
    'page.diagnosisStudio.description': '针对选定的失败执行运行诊断 Agent，并查看工作流进度。',
    'page.diagnosis.title': '诊断结果',
    'page.diagnosis.description': '了解运行失败原因，检查证据并识别可能的根因。',
    'page.traces.title': '追踪',
    'page.traces.description': '在关联视图中追踪 Agent 工作流、模型调用、工具活动与跨系统执行。',
    'page.evaluation.title': '评测',
    'page.evaluation.description': '查看 Agent 运行时执行、校验、工具、安全、延迟、Token 与成本事实。',
    'page.settings.title': '设置',
    'page.settings.description': '项目配置与控制台偏好',
    'settings.projectEnvironment': '项目与环境',
    'settings.platformConnections': '平台连接',
    'settings.appearance': '外观',
    'settings.diagnosisPreference': '诊断偏好',
    'settings.project': '项目',
    'settings.environment': '环境',
    'settings.apiBaseUrl': 'API 基础 URL',
    'settings.demoProject': '演示项目',
    'settings.production': '生产环境',
    'settings.javaPlatform': 'Java Platform',
    'settings.pythonAgentLab': 'Python AgentLab',
    'settings.javaDescription': '用于生产遥测与诊断的 APIOps Java Agent。',
    'settings.pythonDescription': '用于实验与评测的 Python AgentLab SDK。',
    'settings.connected': '已连接',
    'settings.manage': '管理',
    'settings.mockStatus': '以上状态为演示/前端 Mock 数据。',
    'settings.theme': '主题',
    'settings.system': '跟随系统',
    'settings.light': '浅色',
    'settings.dark': '深色',
    'settings.language': '语言',
    'settings.chinese': '中文',
    'settings.english': 'English',
    'settings.compactDensity': '紧凑模式',
    'settings.compactDensityDescription': '减少界面间距，以在同一屏幕显示更多内容',
    'settings.reducedMotion': '减少动态效果',
    'settings.reducedMotionDescription': '减少控制台中的非必要动画和过渡效果',
    'settings.autoDiagnose': '自动诊断失败运行',
    'settings.autoDiagnoseDescription': '当运行失败且结果可用时，自动启动诊断流程',
    'settings.frontendPreferenceNote': '仅保存为前端偏好，不会自动触发后端任务。',
    'settings.languageNote': '语言设置仅适用于 APIOps Console 用户界面。',
    'settings.languageNoteDetail': '后端系统、Agent 和平台继续使用各自的语言。',
  },
}

// `t` covers durable product concepts. `ui` keeps the migration of existing
// page copy lightweight while leaving IDs, enums, payloads, and technical
// implementation names untouched.
const uiTranslations: Record<ConsoleLanguage, Copy> = {
  en: {},
  'zh-CN': {
    Search: '搜索',
    'Search...': '搜索...',
    'Search endpoints': '搜索端点',
    'Search endpoints...': '搜索端点...',
    'Search runs': '搜索运行记录',
    'Search runs...': '搜索运行记录...',
    'Search diagnosis cases': '搜索诊断案例',
    'Search cases...': '搜索案例...',
    'Search traces, workflows, IDs...': '搜索 Trace、工作流或 ID...',
    'Search evaluations...': '搜索评测...',
    'READ-ONLY ARTIFACT': '只读 ARTIFACT',
    'Real result artifact · read-only': '真实结果 artifact · 只读',
    'Metrics and task facts are read from existing persisted results.': '指标和任务事实读取自现有持久化结果。',
    'Reading the selected result artifact.': '正在读取所选结果 artifact。',
    'Loading result': '正在加载结果',
    'Result unavailable': '结果不可用',
    ARTIFACT: 'ARTIFACT',
    UNKNOWN: 'UNKNOWN',
    'Validation Metrics': '校验指标',
    'Tool Metrics': '工具指标',
    'Outcome and Safety': '结果与安全',
    'Latency, Tokens, and Cost': '延迟、Token 与成本',
    'Values are read from the persisted aggregate artifact; missing values are never replaced with zero.': '数值读取自持久化聚合 artifact；缺失值不会替换为 0。',
    'Task success counts copied from the persisted result artifact.': '任务成功计数复制自持久化结果 artifact。',
    values: '个值',
    Pass: '通过',
    'Task Execution Status': '任务执行状态',
    Selected: '已选择',
    Evaluated: '已评测',
    'Evaluated Tasks': '已评测任务',
    'Completed Tasks': '已完成任务',
    'Failed Tasks': '失败任务',
    'Task-level envelopes and EvaluationResult metrics from the persisted artifacts.': '任务级封装和 EvaluationResult 指标读取自持久化 artifact。',
    'Loading task results': '正在加载任务结果',
    'Task results unavailable': '任务结果不可用',
    'No task results are available.': '暂无任务结果。',
    'Tool Exact Match': '工具精确匹配',
    'Failure Reason': '失败原因',
    'persisted task results': '个持久化任务结果',
    'Failure and Uncertainty Digest': '失败与不确定性摘要',
    'Failure reasons and UNKNOWN task outcomes are copied from the task artifacts.': '失败原因和 UNKNOWN 任务结果复制自任务 artifact。',
    'No task failures or unknown outcomes are recorded.': '未记录任务失败或未知结果。',
    'No failure code': '无失败代码',
    'Configuration and artifact references captured for this existing result.': '此现有结果中记录的配置和 artifact 引用。',
    'Artifact References': 'Artifact 引用',
    'Run artifact': 'Run artifact',
    'Reproducibility artifact': '可复现性 artifact',
    references: '个引用',
    All: '全部',
    Success: '成功',
    Failed: '失败',
    Running: '运行中',
    Cancelled: '已取消',
    Completed: '已完成',
    'Completed 2 min ago': '已完成 2 分钟前',
    'Completed 11 min ago': '已完成 11 分钟前',
    'Completed 18 min ago': '已完成 18 分钟前',
    'Completed 1 hr ago': '已完成 1 小时前',
    'Running · 28 / 40 tasks': '运行中 · 28 / 40 个任务',
    'Failed 35 min ago': '失败 35 分钟前',
    Tool: '工具',
    Model: '模型',
    'More actions': '更多操作',
    'View all': '查看全部',
    'View details': '查看详情',
    'View all runs': '查看全部运行记录',
    'View all activity': '查看全部活动',
    'Open in Studio': '在 Studio 中打开',
    'Open in Traces': '在 Traces 中打开',
    'Open in Diagnosis Studio': '在诊断工作台中打开',
    'View Diagnosis Result': '查看诊断结果',
    'View Report': '查看报告',
    Export: '导出',
    More: '更多',
    Copy: '复制',
    Download: '下载',
    Close: '关闭',
    Run: '运行',
    'Good afternoon': '下午好',
    'Agentic APIOps workspace': 'Agentic APIOps 工作台',
    'Last 24 hours': '最近 24 小时',
    'Refresh overview': '刷新概览',
    'Live platform summary': '实时平台摘要',
    'Open detail pages': '打开详细页面',
    'Open Grafana': '打开 Grafana',
    'Key metrics': '关键指标',
    'Overview details': '概览详情',
    'System Health': '系统健康',
    'Platform health': '平台健康',
    'Live health sources': '实时健康来源',
    'System Status': '系统状态',
    'Java Platform': 'Java Platform',
    'Python AgentLab': 'Python AgentLab',
    'Execution & Security Authority': '执行与安全权威来源',
    'Agent Workflow / Diagnosis / Trace / Evaluation': 'Agent 工作流 / 诊断 / Trace / 评测',
    Checking: '检查中',
    'Checking service availability...': '正在检查服务可用性…',
    'The health endpoint could not be reached.': '无法访问健康检查端点。',
    'The health endpoint reported the service as unavailable.': '健康检查端点报告服务不可用。',
    'The health endpoint reported a degraded status.': '健康检查端点报告服务已降级。',
    'The service is available.': '服务可用。',
    'The health response did not include a recognized status.': '健康响应未包含可识别的状态。',
    Healthy: '健康',
    Degraded: '已降级',
    Unknown: '未知',
    'Last checked': '最近检查',
    'Console observation': 'Console 观测',
    'Observation time recorded by the Console when the health request completed.': '观测时间由 Console 在健康请求完成时记录。',
    Ready: '就绪',
    'Run summary': '运行摘要',
    'Java /test-runs': 'Java /test-runs',
    'Java Runs unavailable': 'Java 运行记录不可用',
    'Access denied for the current project.': '当前项目无访问权限。',
    'No fallback data is shown.': '未显示回退数据。',
    'Recent Java runs unavailable': '最近 Java 运行记录不可用',
    'Loading recent Java runs...': '正在加载最近 Java 运行记录…',
    'No recent runs': '暂无最近运行记录',
    'The Java Platform returned no persisted runs for this project.': 'Java Platform 未返回当前项目的持久化运行记录。',
    Created: '创建时间',
    'Runtime Evaluation summary': 'Runtime Evaluation 摘要',
    'Python AgentLab API': 'Python AgentLab API',
    'Runtime runs': 'Runtime 运行数',
    'Execution success': '执行成功率',
    'Approval required': '需要审批',
    'Read-only values supplied by Runtime Evaluation API.': '以上只读数值由 Runtime Evaluation API 提供。',
    'Open Evaluation': '打开评测',
    'Runtime Evaluation unavailable': 'Runtime Evaluation 不可用',
    'Loading Runtime Evaluation summary...': '正在加载 Runtime Evaluation 摘要…',
    'Recent failures / attention': '最近失败 / 待关注',
    'Recent failure': '最近失败',
    'Runtime Evaluation needs attention': 'Runtime Evaluation 需要关注',
    'Runtime Evaluation failed executions': 'Runtime Evaluation 失败执行',
    'runs awaiting approval': '条运行等待审批',
    'No recent failures or attention items.': '暂无最近失败或待关注项。',
    'The live health source reported an attention state.': '实时健康来源报告了需要关注的状态。',
    'The health source is unavailable; status remains UNKNOWN.': '健康来源不可用；状态保持 UNKNOWN。',
    'vs yesterday': '较昨日',
    'Agentic Pipeline Preview': 'Agentic Pipeline 预览',
    'Recent Runs': '最近运行记录',
    'Recent Activity': '最近活动',
    'View all Runs': '查看全部运行记录',
    'View all Diagnosis': '查看全部诊断',
    'Recent Diagnosis': '最近诊断',
    'Recent diagnosis unavailable': '最近诊断不可用',
    'Loading recent diagnosis...': '正在加载最近诊断…',
    'No recent diagnosis': '暂无最近诊断',
    'Python AgentLab returned no diagnosis executions for this project.': 'Python AgentLab 未返回当前项目的诊断执行记录。',
    'Source run': '来源运行',
    'Diagnosis in progress': '诊断进行中',
    'Diagnosis failed': '诊断失败',
    'Diagnosis rejected': '诊断已拒绝',
    'Summary unavailable': '摘要不可用',
    Rejected: '已拒绝',
    Time: '时间',
    Endpoint: '端点',
    Method: '方法',
    Status: '状态',
    Duration: '耗时',
    Environment: '环境',
    'Recent Agent Activity': '最近 Agent 活动',
    'API Explorer': 'API 浏览器',
    'API Studio views': 'API Studio 视图',
    Documents: '文档',
    'OpenAPI Documents': 'OpenAPI 文档',
    'Select a document version to inspect its endpoints.': '选择文档版本以查看其端点。',
    'Import OpenAPI': '导入 OpenAPI',
    Document: '文档',
    'Current Document': '当前文档',
    'Document Version': '文档版本',
    'OpenAPI version': 'OpenAPI 版本',
    Updated: '更新时间',
    endpoints: '个端点',
    'Parsing document...': '正在解析文档…',
    'Import ready': '导入就绪',
    'Import failed': '导入失败',
    'Import completed; documents and endpoints refreshed from Java Platform.': '导入完成；已从 Java Platform 刷新文档和端点。',
    'Loading documents...': '正在加载文档…',
    'OpenAPI documents unavailable': 'OpenAPI 文档不可用',
    'Unable to load OpenAPI documents.': '无法加载 OpenAPI 文档。',
    'No OpenAPI documents found.': '未找到 OpenAPI 文档。',
    'Select a document after the document list is available.': '文档列表加载后请选择一个文档。',
    'Add endpoint': '添加端点',
    'No endpoints found.': '未找到端点。',
    'Edit endpoint': '编辑端点',
    'View OpenAPI': '查看 OpenAPI',
    'Send Request': '发送请求',
    'Endpoint metadata': '端点元数据',
    Description: '描述',
    OperationId: '操作 ID',
    Service: '服务',
    Path: '路径',
    Version: '版本',
    Security: '安全性',
    'Security Requirements': '安全要求',
    Servers: '服务地址',
    Tags: '标签',
    'Request details': '请求详情',
    'Request details tabs': '请求详情标签',
    Parameters: '参数',
    'Request Body': '请求体',
    Responses: '响应',
    Examples: '示例',
    Schema: 'Schema',
    Example: '示例',
    'No parameters are defined for this operation.': '此操作未定义参数。',
    'No request schema is defined for this operation.': '此操作未定义请求 Schema。',
    'Response schemas and examples are shown in the Responses panel.': '响应 Schema 和示例显示在“响应”面板中。',
    'No examples are defined for this operation.': '此操作未定义示例。',
    'No response schema is available.': '暂无响应 Schema。',
    'No response example.': '暂无响应示例。',
    'Content Type': '内容类型',
    'View Schema': '查看 Schema',
    'This mock view is read-only.': '此 Mock 视图为只读。',
    'Add Response': '添加响应',
    'TestCase Generator': '测试用例生成器',
    'Agent Runtime': 'Agent 运行时',
    Strategy: '策略',
    'Metadata evidence is not available.': '暂无可用的元数据证据。',
    'Requires a documented 2xx response.': '需要文档中存在 2xx 响应。',
    'Requires a documented required request field.': '需要文档中存在必填请求字段。',
    'Requires a documented request boundary.': '需要文档中存在请求边界约束。',
    'Requires a documented security requirement.': '需要文档中存在安全要求。',
    'Requires explicit idempotency documentation.': '需要文档明确说明幂等性。',
    'Requires a documented non-2xx response.': '需要文档中存在非 2xx 响应。',
    Configuration: '配置',
    Auth: '认证',
    'Use Valid Token': '使用有效令牌',
    'Omit Token': '不使用令牌',
    'Data Source': '数据源',
    Static: '静态',
    'Generated Fixture': '生成的 Fixture',
    Unavailable: '不可用',
    'Generating...': '正在生成...',
    'Generate Test Case': '生成测试用例',
    'Generated by': '生成来源',
    'Generated TestCase DSL': '已生成 TestCase DSL',
    ACCEPTED: '已通过',
    GENERATING: '生成中',
    VALIDATING: '校验中',
    REPAIRING: '修复中',
    REJECTED: '未通过',
    'Agent output is being generated.': '正在生成 Agent 输出。',
    'Validating candidate against the shared TestCase DSL.': '正在根据共享 TestCase DSL 校验候选结果。',
    'Repairing the candidate after validation feedback.': '根据校验反馈修复候选结果。',
    'Candidate rejected after the bounded repair attempt.': '候选结果在有限次数修复后仍未通过。',
    'Candidate accepted after shared TestCase validation.': '候选结果通过共享 TestCase 校验。',
    'Repair attempt': '修复尝试',
    'Generate a TestCase to inspect the validated DSL.': '生成一个 TestCase 以查看经过校验的 DSL。',
    'Happy Path': '成功路径',
    'Missing Required': '缺少必填项',
    Boundary: '边界条件',
    'Auth Failure': '认证失败',
    Idempotency: '幂等性',
    'Business Error': '业务错误',
    Copied: '已复制',
    'Runs Explorer': '运行记录浏览器',
    'New run': '新建运行',
    'Run filters': '运行记录筛选',
    'Runs list': '运行记录列表',
    runs: '运行记录',
    'No runs match the current filters.': '没有符合当前筛选条件的运行记录。',
    'Run detail': '运行详情',
    'Run detail tabs': '运行详情标签',
    'Run overview': '运行概览',
    'Run created': '运行已创建',
    'Assertion passed': '断言已通过',
    'Java execution facts': 'Java 执行事实',
    API: 'API',
    'Report ID': '报告 ID',
    'Test Report': '测试报告',
    'Run → Case → Step → Assertion': '运行 → 测试用例 → 步骤 → 断言',
    Case: '测试用例',
    'Repeated executions': '重复执行',
    executions: '次执行',
    'Execution count': '执行次数',
    'Total duration': '总耗时',
    'Average duration': '平均耗时',
    'Raw executions': '原始执行',
    'Raw assertions': '原始断言',
    'Presentation group for consecutive equivalent executions.': '连续等价执行的展示分组。',
    'Failure type': '失败类型',
    'Connection Error': '连接失败',
    'No HTTP response': '未收到 HTTP 响应',
    'No response': '无响应',
    'No response body recorded.': '未记录响应正文。',
    'Assertions are shown in the Assertions tab.': '断言详情显示在“断言”标签中。',
    'No assertions recorded.': '未记录断言。',
    'No step results recorded.': '未记录步骤结果。',
    'Execution details captured for this mock run': '此 Mock 运行的执行详情',
    'Executed by': '执行方',
    'Copy run ID': '复制运行 ID',
    Started: '已开始',
    'HTTP Status': 'HTTP 状态',
    Assertions: '断言',
    'Execution Summary': '执行摘要',
    'Mock metadata': 'Mock 元数据',
    Timeline: '时间线',
    'Execution trace': '执行追踪',
    'Request does not include a body.': '此请求不包含请求体。',
    'This request does not include a body.': '此请求不包含请求体。',
    'Assertions evaluated': '已评估断言',
    'checks ran...': '项检查已运行...',
    'checks ran against the response contract.': '项检查针对响应契约运行。',
    passed: '通过',
    Expected: '预期值',
    Actual: '实际值',
    Request: '请求',
    Response: '响应',
    'Captured request sent to the selected endpoint.': '已记录发送到所选端点的请求。',
    'Captured response returned by the selected endpoint.': '已记录所选端点返回的响应。',
    'Test case': '测试用例',
    'Triggered by': '触发方式',
    'Failure investigations': '失败调查',
    'Diagnosis Cases': '诊断案例',
    'Diagnosis filters': '诊断筛选',
    'Diagnosis case list': '诊断案例列表',
    'Diagnosis result': '诊断结果',
    'No diagnosis result is available for this execution.': '此执行暂无诊断结果。',
    'The selected run': '所选运行',
    'has no mock DiagnosisReport yet.': '尚无对应的 Mock DiagnosisReport。',
    'Evidence and context inspector': '证据与上下文检查器',
    'Affected Area': '影响区域',
    Priority: '优先级',
    'Execution facts': '执行事实',
    'Run context': '运行上下文',
    'Failure analysis': '失败分析',
    'Failure Summary': '失败摘要',
    'Agent diagnosis': 'Agent 诊断',
    'Likely Root Cause': '可能的根因',
    'Supporting reasoning': '支持性推理',
    'Recommended next step': '建议下一步',
    'Suggested Fix': '建议修复',
    'Run ID': '运行 ID',
    'Executed At': '执行时间',
    'Re-run Diagnosis': '重新运行诊断',
    'Evidence & Context': '证据与上下文',
    'Investigation details': '调查详情',
    'Close evidence inspector': '关闭证据检查器',
    Evidence: '证据',
    'Primary signals': '主要信号',
    'Assertion Result': '断言结果',
    'Response Payload': '响应载荷',
    'HTTP response body': 'HTTP 响应体',
    'Evidence Sources': '证据来源',
    available: '可用',
    'Tool Activity': '工具活动',
    'Tool Activity / Audit': '工具活动 / Audit',
    'Mock trace': 'Mock Trace',
    Context: '上下文',
    'Context & Evidence': '上下文与证据',
    'Step facts': '步骤事实',
    'Observed model-call facts only; answer quality belongs in Evaluation.': '这里只展示模型调用事实；回答质量属于评测范围。',
    'Python intent facts and Java Tool Gateway authority facts remain separate.': 'Python 意图事实与 Java Tool Gateway 权威事实保持分离。',
    'Context and evidence visible to the workflow; diagnosis conclusions belong in Diagnosis.': '此处展示工作流可见的上下文与证据；诊断结论属于诊断结果。',
    'Model Call': '模型调用',
    Provider: 'Provider',
    Runtime: '运行时',
    'Model Call ID': 'Model Call ID',
    'Input Tokens': '输入 Token',
    'Output Tokens': '输出 Token',
    'Total Tokens': '总 Token',
    Attempt: '尝试次数',
    'Error Type': '错误类型',
    Phase: '阶段',
    'Tool Intent ID': 'Tool Intent ID',
    'Tool Call ID': 'Tool Call ID',
    'Request ID': 'Request ID',
    'Preflight Decision': 'Preflight 决策',
    'Approval Outcome': '审批结果',
    'Authorization Result': '授权结果',
    'Guard Decision': 'Guard 决策',
    Sanitized: '已脱敏',
    Truncated: '已截断',
    'Violation Code': '违规代码',
    'Result Summary': '结果摘要',
    'HITL / Approval': 'HITL / 审批',
    Decision: '决策',
    'RAG Query ID': 'RAG Query ID',
    Query: '查询',
    'Context Sources': '上下文来源',
    'Context Budget': '上下文预算',
    'Memory ID': 'Memory ID',
    'Document ID': 'Document ID',
    'Chunk ID': 'Chunk ID',
    Location: '位置',
    Relevance: '相关性',
    Citation: '引用',
    'Collected inputs': '已收集输入',
    'Evidence Items': '证据项',
    'Context Size': '上下文大小',
    'Model Calls': '模型调用',
    'Tool Calls': '工具调用',
    Identity: '身份标识',
    'Traceable IDs': '可追踪 ID',
    'Diagnosis Confidence': '诊断置信度',
    'Back to Runs': '返回运行记录',
    'Back to Diagnosis': '返回诊断结果',
    'Back to': '返回',
    'Java Runner execution': 'Java Runner 执行',
    'View Trace': '查看 Trace',
    'Selected execution': '已选执行',
    'Failed execution': '失败执行',
    'View Test Report': '查看测试报告',
    'Select an agent implementation': '选择 Agent 实现',
    Recommended: '推荐',
    'Workflow Progress': '工作流进度',
    'Human Approval Required': '需要人工审批',
    'Execution status': '执行状态',
    'Proposed Arguments': '建议参数',
    'Approval Scope': '审批范围',
    'Exact intent binding': '精确意图绑定',
    Reject: '拒绝',
    'Edit & Approve': '编辑并批准',
    'Apply & Approve': '应用并批准',
    Approve: '批准',
    'Execution context': '执行上下文',
    'Key Evidence': '关键证据',
    'All Evidence': '全部证据',
    'Execution Identity': '执行身份',
    Source: '来源',
    'Workflow Context': '工作流上下文',
    'Trace Explorer': 'Trace 浏览器',
    'Trace filters': 'Trace 筛选',
    'No traces found.': '未找到 Trace。',
    'Load more': '加载更多',
    Identities: '身份标识',
    'Correlated Systems': '关联系统',
    'Trace Tree + Waterfall': 'Trace 树与瀑布图',
    'Expand all': '全部展开',
    'Collapse all': '全部收起',
    'Relative time': '相对时间',
    'Absolute time': '绝对时间',
    Step: '步骤',
    'Start Time': '开始时间',
    'Selected Step': '已选步骤',
    'View in logs': '在日志中查看',
    'Selected step details': '已选步骤详情',
    Overview: '概览',
    Input: '输入',
    Output: '输出',
    Attributes: '属性',
    'No data available': '暂无数据',
    'No activity yet': '暂无活动',
    'No results found.': '未找到结果。',
    'Evaluation Runs': '评测运行',
    'Create evaluation': '创建评测',
    'Evaluation filters': '评测筛选',
    'Evaluation Run': '评测运行',
    'Core Metrics': '核心指标',
    'Category Performance': '分类表现',
    'Evaluation Configuration': '评测配置',
    'View Full Configuration': '查看完整配置',
    'Case Results': '案例结果',
    Type: '类型',
    Result: '结果',
    Columns: '列',
    'Choose case columns': '选择案例列',
    'Recent Cases': '最近案例',
    'Evaluation Run Overview': '评测运行概览',
    'Evaluation Scope': '评测范围',
    'Tasks Selected': '已选任务',
    'Agent Run Example': 'Agent 运行示例',
    'Java Runner Run ID': 'Java Runner 运行 ID',
    'Trace Correlation': 'Trace 关联',
    'Quick Links': '快速入口',
    'APIOps home': 'APIOps 首页',
    'Approval applies only to this exact intent and argument snapshot. It does not grant permanent permission.': '审批仅适用于此意图及参数快照，不授予永久权限。',
    cases: '个案例',
    Cost: '成本',
    Diagnosis: '诊断',
    'Diagnosis execution stopped because the requested tool action was rejected.': '诊断执行已停止，因为请求的工具操作被拒绝。',
    'Diagnosis runtime': '诊断运行时',
    'End Time': '结束时间',
    Evaluation: '评测',
    'Evaluation Readout': '评测概览',
    'Evaluation status filters': '评测状态筛选',
    'Evaluation views': '评测视图',
    'Execution evidence views': '执行证据视图',
    'Failures, timeouts, and unavailable evaluations retain their original status semantics.': '失败、超时和不可用评测保留原始状态语义。',
    'Inspect trace correlation': '检查 Trace 关联',
    'Java Agent completes through structured diagnosis and citation validation. Human approval is not part of this flow.': 'Java Agent 通过结构化诊断和引用校验完成流程；该流程不包含人工审批。',
    Latency: '延迟',
    Metric: '指标',
    'No evaluation runs match the current filters.': '没有符合当前筛选条件的评测运行。',
    'No traces match the current filters.': '没有符合当前筛选条件的 Trace。',
    'Open evaluation result': '打开评测结果',
    'Order Service Demo': '订单服务演示',
    Page: '页',
    'Parent Step': '父步骤',
    'Primary navigation': '主导航',
    'Prompt Version': 'Prompt 版本',
    'Proposed tool arguments': '建议的工具参数',
    Reason: '原因',
    'Revalidating intent and continuing the workflow…': '正在重新校验意图并继续工作流…',
    Risk: '风险',
    'Run Diagnosis Again': '再次运行诊断',
    'Runtime and usage values are read-only results supplied by the evaluation run.': '运行时与用量数据是评测运行提供的只读结果。',
    'Safety Violations': '安全违规',
    'Search cases': '搜索案例',
    'Search evaluations': '搜索评测',
    'Search traces': '搜索 Trace',
    Select: '选择',
    signals: '个信号',
    'Start Diagnosis Again': '开始再次诊断',
    steps: '步骤',
    tasks: '个任务',
    to: '至',
    Trace: 'Trace',
    'Trace ID': 'Trace ID',
    'View all cases': '查看全部案例',
    'Waterfall time mode': '瀑布图时间模式',
    'Workflow / Implementation': '工作流 / 实现',
    iteration: '迭代',
    'All Types': '全部类型',
    'Assertion Failed': '断言失败',
    'Execution Failed': '执行失败',
    Timeout: '超时',
    'Waiting for human approval': '等待人工审批',
    'Diagnosis workflow is resuming': '诊断工作流正在恢复',
    'DiagnosisReport is ready': 'DiagnosisReport 已就绪',
    'Diagnosis execution stopped': '诊断执行已停止',
    'No human approval is required': '无需人工审批',
    'Assertions passed': '断言已通过',
    'Run started': '运行已开始',
    'Request sent': '请求已发送',
    'Response received': '已收到响应',
    'Assertion failed': '断言失败',
    'Run completed': '运行已完成',
    'Run pending': '运行待处理',
    'Run timed out': '运行超时',
    'Execution failed': '执行失败',
    'Run cancelled': '运行已取消',
    'Run is waiting to start': '运行等待开始',
    'Run was cancelled before completion': '运行在完成前已取消',
    'Run is still in progress': '运行仍在进行中',
    'Started At': '开始时间',
    'Completed At': '完成时间',
    Cases: '案例',
    Implementation: '实现',
    Evaluator: '评测器',
    Judge: 'Judge',
    Prompt: 'Prompt',
    Metrics: '指标',
    'All Evidence (8)': '全部证据 (8)',
    'Failure Diagnosis': '失败诊断',
    'TestCase Generation': '测试用例生成',
    'Tool Safety': '工具安全',
    'RAG Evidence': 'RAG 证据',
    'E2E APIOps': '端到端 APIOps',
    'End-to-End APIOps': '端到端 APIOps',
    'Valid JSON': 'JSON 有效',
    'Schema Valid': 'Schema 有效',
    'Contract Accepted': '契约已接受',
    'Generate TestCase': '生成测试用例',
    Collect: '采集',
    Create: '创建',
    Validate: '校验',
    Execute: '执行',
    Analyze: '分析',
    Resolve: '处理',
    'API Endpoints': 'API 端点',
    'Test Runs': '测试运行',
    'Success Rate': '成功率',
    'Agent Runs': 'Agent 运行数',
    Actions: '操作',
    Steps: '步骤',
    'Diagnosis Agent Run': '诊断 Agent 运行',
    Metadata: '元数据',
    Generator: '生成器',
    Validator: '校验器',
    Runner: 'Runner',
    'Tool Gateway': 'Tool Gateway',
    'This module is reserved for the next console phase.': '此模块预留给控制台后续阶段。',
    'APIOps workspace': 'APIOps 工作台',
    'Load TestReport': '加载 TestReport',
    'Read Java Runner result': '读取 Java Runner 结果',
    'Build Context': '构建上下文',
    'Assemble evidence and metadata': '整理证据与元数据',
    'Analyze Failure': '分析失败',
    'Diagnosis workflow reasoning': '诊断工作流推理',
    'Tool Approval': '工具审批',
    Pending: '待处理',
    'Load ContextPack': '加载 ContextPack',
    'Load structured context': '加载结构化上下文',
    'Invoke DiagnosisAgent': '调用 DiagnosisAgent',
    'Spring AI diagnosis call': 'Spring AI 诊断调用',
    'Structured Diagnosis': '结构化诊断',
    'Validate DiagnosisReport shape': '校验 DiagnosisReport 结构',
    'Citation Validation': '引用校验',
    'Validate evidence references': '校验证据引用',
    'DiagnosisReport ready': 'DiagnosisReport 已就绪',
    Showing: '显示',
    of: '共',
    'Previous page': '上一页',
    'Next page': '下一页',
  },
}

type ConsoleLanguageContextValue = {
  language: ConsoleLanguage
  setLanguage: (language: ConsoleLanguage) => void
  t: (key: string) => string
  ui: (text: string) => string
}

const ConsoleLanguageContext = createContext<ConsoleLanguageContextValue | null>(null)

function getInitialLanguage(): ConsoleLanguage {
  if (typeof window === 'undefined') return 'en'

  try {
    return window.localStorage.getItem(LANGUAGE_STORAGE_KEY) === 'zh-CN' ? 'zh-CN' : 'en'
  } catch {
    return 'en'
  }
}

export function ConsoleLanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<ConsoleLanguage>(getInitialLanguage)

  useEffect(() => {
    try {
      window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language)
    } catch {
      // The UI remains usable when storage is unavailable.
    }
  }, [language])

  const value = useMemo<ConsoleLanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key) => translations[language][key] ?? key,
    ui: (text) => language === 'zh-CN' ? uiTranslations[language][text] ?? text : text,
  }), [language])

  return <ConsoleLanguageContext.Provider value={value}>{children}</ConsoleLanguageContext.Provider>
}

export function useConsoleLanguage() {
  const context = useContext(ConsoleLanguageContext)
  if (!context) throw new Error('useConsoleLanguage must be used within ConsoleLanguageProvider')
  return context
}
