"""Internal Tool-use catalog and routing boundaries."""

from .core import (
    DuplicateToolError,
    FakeToolGatewayAdapter,
    InvalidGatewayResultError,
    ToolAdapterUnavailableError,
    ToolCatalog,
    ToolCatalogError,
    ToolContractMismatchError,
    ToolDescriptor,
    ToolGatewayAdapter,
    ToolGatewayAuthenticationError,
    ToolGatewayAuthorizationError,
    ToolGatewayNotFoundError,
    ToolGatewayTimeoutError,
    ToolGatewayTransportError,
    ToolIntent,
    ToolRouter,
    UnapprovedToolError,
    UnknownToolError,
    map_tool_intent,
)
from .risk import ToolRisk, ToolRiskClassifier

__all__ = [
    "DuplicateToolError",
    "FakeToolGatewayAdapter",
    "InvalidGatewayResultError",
    "map_tool_intent",
    "ToolAdapterUnavailableError",
    "ToolCatalog",
    "ToolCatalogError",
    "ToolContractMismatchError",
    "ToolDescriptor",
    "ToolGatewayAdapter",
    "ToolGatewayAuthenticationError",
    "ToolGatewayAuthorizationError",
    "ToolGatewayNotFoundError",
    "ToolGatewayTimeoutError",
    "ToolGatewayTransportError",
    "ToolIntent",
    "ToolRouter",
    "ToolRisk",
    "ToolRiskClassifier",
    "UnapprovedToolError",
    "UnknownToolError",
]
